// Tipos y reglas puras del dominio. Sin dependencias de UI, datos ni framework.
export * from './ids.js';
export * from './errors.js';
export * from './note.js';
export * from './note-text.js';
export * from './markdown-import.js';
export * from './note-groups.js';
export * from './note-query.js';
export * from './folder.js';
export * from './user.js';
export * from './auth.js';
export * from './device.js';
export * from './share.js';
export * from './sync.js';
export * from './crypto.js';
export * from './sync-protocol.js';
export * from './settings.js';
export * from './storage.js';
export * from './validation.js';
